version: '3.3'

services:
  db:
    image: postgres:11.1
    network_mode: bridge
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: bind
        source: /vagrant/postgresql/chinook_data.sql
        target: /docker-entrypoint-initdb.d/chinook_data.sql
    restart: always
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: chinook
  web:
    build: .
    network_mode: bridge
    ports:
      - "8000:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chinook
      SPRING_DATASOURCE_USERNAME: vagrant
      SPRING_DATASOURCE_PASSWORD: vagrant

volumes:
  db_data:
